# Generated by Django 2.0.3 on 2018-03-21 15:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_stars', models.FloatField(verbose_name='图片的平均得分')),
                ('date_update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '图片得分',
                'verbose_name_plural': '图片得分',
                'db_table': 'db_score',
            },
        ),
        migrations.CreateModel(
            name='UserRateing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(choices=[(1, '1 星'), (2, '2 星'), (3, '3 星'), (4, '4 星'), (5, '5 星')], verbose_name='得分')),
                ('date_evaluation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评分时间')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='image.Image', verbose_name='评价的图片')),
            ],
            options={
                'verbose_name': '用户评分',
                'verbose_name_plural': '用户评分',
                'db_table': 'db_source_rateing',
            },
        ),
    ]
