# Generated by Django 2.0.3 on 2018-03-20 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image', '0002_auto_20180320_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='image.Image', verbose_name='图片')),
            ],
            options={
                'verbose_name': '图片评分',
                'verbose_name_plural': '图片评分',
                'db_table': 'db_source',
            },
        ),
        migrations.CreateModel(
            name='UserRateing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(choices=[('1', '1 星'), ('2', '2 星'), ('3', '3 星'), ('4', '4 星'), ('5', '5 星')], verbose_name='得分')),
                ('date_evaluation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评分时间')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='image.Image', verbose_name='评价的图片')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='评价的用户')),
            ],
            options={
                'verbose_name': '用户评分',
                'verbose_name_plural': '用户评分',
                'db_table': 'db_source_rateing',
            },
        ),
    ]
