# Generated by Django 2.0.3 on 2018-03-21 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('score', '0001_initial'),
        ('image', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userrateing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='评价的用户'),
        ),
        migrations.AddField(
            model_name='score',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='image.Image', verbose_name='图片'),
        ),
    ]
