# Generated by Django 2.0.3 on 2018-03-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': '评分', 'verbose_name_plural': '评分'},
        ),
        migrations.AlterField(
            model_name='userrateing',
            name='point',
            field=models.IntegerField(choices=[('1', '1星'), ('2', '2 星'), ('3', '3 星'), ('4', '4 星'), ('5', '5 星')], verbose_name='得分'),
        ),
    ]
