# Generated by Django 2.0.3 on 2018-03-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_auto_20180320_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrateing',
            name='point',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], verbose_name='得分'),
        ),
    ]
