# Generated by Django 2.0.3 on 2018-03-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='图片ID')),
                ('name', models.CharField(max_length=50, verbose_name='图片名')),
                ('info', models.TextField(verbose_name='图片描述')),
                ('url', models.URLField(max_length=500, verbose_name='图片链接')),
                ('url_thumb', models.URLField(max_length=500, verbose_name='缩略图片链接')),
                ('width', models.IntegerField(verbose_name='图片宽度')),
                ('height', models.IntegerField(verbose_name='图片高度')),
                ('type', models.CharField(choices=[('0', 'jpg'), ('1', 'png'), ('2', 'gif'), ('3', 'bmp'), ('4', 'svg')], max_length=10, verbose_name='图片格式')),
                ('category', models.OneToOneField(on_delete='CASCADE', to='category.Category', verbose_name='图片分类')),
                ('tags', models.ManyToManyField(to='tag.Tag', verbose_name='图片标签')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
                'db_table': 'db_image',
            },
        ),
    ]
