# Generated by Django 2.0.4 on 2018-04-23 21:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True, verbose_name='图片展示顺序')),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'db_carousel',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名')),
                ('count', models.IntegerField(default=0, verbose_name='分类数量')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 'db_category',
            },
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '图片分类',
                'verbose_name_plural': '图片分类',
                'db_table': 'db_category_image',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='图片名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='图片描述')),
                ('url', models.URLField(max_length=500, verbose_name='图片链接')),
                ('url_thumb', models.URLField(max_length=500, verbose_name='缩略图片链接')),
                ('width', models.IntegerField(verbose_name='图片宽度')),
                ('height', models.IntegerField(verbose_name='图片高度')),
                ('type', models.CharField(choices=[('jpg', 'JPG 图片'), ('png', 'PNG 图片'), ('gif', 'GIF 图片'), ('bmp', 'BMP 图片'), ('svg', 'SVG 图片')], max_length=10, verbose_name='图片格式')),
                ('click', models.IntegerField(default=0, verbose_name='点击次数')),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now, verbose_name='图片添加时间')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
                'db_table': 'db_image',
            },
        ),
        migrations.CreateModel(
            name='ImageScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_stars', models.FloatField(verbose_name='图片的平均得分')),
                ('date_update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '图片得分',
                'verbose_name_plural': '图片得分',
                'db_table': 'db_image_score',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(choices=[(1, '1 星'), (2, '2 星'), (3, '3 星'), (4, '4 星'), (5, '5 星')], verbose_name='得分')),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评分时间')),
            ],
            options={
                'verbose_name': '用户评分',
                'verbose_name_plural': '用户评分',
                'db_table': 'db_rating',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'db_tag',
            },
        ),
        migrations.CreateModel(
            name='TagImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.Image', verbose_name='图片')),
                ('tags', models.ManyToManyField(to='image.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '用户添加的图片标签',
                'verbose_name_plural': '用户添加的图片标签',
                'db_table': 'db_tag_image',
            },
        ),
    ]
