# Generated by Django 2.0.3 on 2018-03-22 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrateing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='评价的用户'),
        ),
        migrations.AddField(
            model_name='tagimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.Image', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='tagimage',
            name='tags',
            field=models.ManyToManyField(to='image.ImageTag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='tagimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='imagescore',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='image.Image', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='hotimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.Image', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='categoryimage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.ImageCategory', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='categoryimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.Image', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='categoryimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
