# Generated by Django 2.0.3 on 2018-03-21 15:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'db_tag',
            },
        ),
        migrations.CreateModel(
            name='TagImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.Image', verbose_name='图片')),
                ('tag', models.ManyToManyField(to='tag.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '用户添加的图片标签',
                'verbose_name_plural': '用户添加的图片标签',
                'db_table': 'db_tag_image',
            },
        ),
    ]
