# Generated by Django 2.0.3 on 2018-03-20 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image', '0002_auto_20180320_1723'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.Image', verbose_name='图片')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.Tag', verbose_name='标签')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '图片标签',
                'verbose_name_plural': '图片标签',
                'db_table': 'db_image_tag',
            },
        ),
    ]
