# Generated by Django 2.0.3 on 2018-03-20 18:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20180320_1723'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag', '0002_imagetag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageTag',
            new_name='TagImage',
        ),
        migrations.AlterModelTable(
            name='tagimage',
            table='db_tag_image',
        ),
    ]
