# Generated by Django 2.0.3 on 2018-03-20 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_auto_20180320_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
    ]
