# Generated by Django 2.0.3 on 2018-03-21 15:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名')),
                ('count', models.IntegerField(default=0, verbose_name='分类数量')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 'db_category',
            },
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category', verbose_name='分类')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.Image', verbose_name='图片')),
            ],
            options={
                'verbose_name': '图片分类',
                'verbose_name_plural': '图片分类',
                'db_table': 'db_category_image',
            },
        ),
    ]
