# Generated by Django 2.0.3 on 2018-03-15 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('username', models.CharField(default='', max_length=50, verbose_name='用户名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('image', models.ImageField(blank=True, default='/static/resource/user_image/default.png', null=True, upload_to='resource/user_image', verbose_name='头像')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('is_active', models.BooleanField(default=False, verbose_name='用户是否可以使用')),
                ('sex', models.CharField(blank=True, choices=[('1', '男'), ('0', '女'), ('-1', '中')], default='中', max_length=10, null=True, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, max_length=10, null=True, verbose_name='生日')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='地址')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('information', models.TextField(blank=True, null=True, verbose_name='信息')),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now, verbose_name='注册时间')),
                ('last_login', models.DateTimeField(default=datetime.datetime.now, verbose_name='最后登录时间')),
                ('type', models.CharField(choices=[('0', 'default'), ('1', 'vip')], default='0', max_length=50, verbose_name='用户类型')),
                ('integral', models.IntegerField(default=100, verbose_name='用户积分')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'db_user',
            },
        ),
        migrations.CreateModel(
            name='UserAuthentication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(max_length=50, verbose_name='验证码')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('send_type', models.CharField(choices=[('1', '注册'), ('2', '找回密码')], max_length=10, verbose_name='验证类型')),
                ('send_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间')),
                ('expired_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='过期时间')),
                ('is_active', models.CharField(choices=[('0', '未激活'), ('1', '已激活')], default='0', max_length=10, verbose_name='激活链接是否点击')),
            ],
            options={
                'verbose_name': '用户验证',
                'verbose_name_plural': '用户验证',
                'db_table': 'db_user_authentication',
            },
        ),
    ]
