# Generated by Django 2.0.3 on 2018-03-19 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthentication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(max_length=50, verbose_name='验证码')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('send_type', models.CharField(choices=[('1', '注册'), ('2', '找回密码')], max_length=10, verbose_name='验证类型')),
                ('send_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间')),
                ('expired_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='过期时间')),
                ('is_active', models.CharField(choices=[('0', '未激活'), ('1', '已激活')], default='0', max_length=10, verbose_name='激活链接是否点击')),
            ],
            options={
                'verbose_name': '用户验证',
                'verbose_name_plural': '用户验证',
                'db_table': 'db_user_authentication',
            },
        ),
    ]
