# Generated by Django 2.0.3 on 2018-03-11 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nick_name',
            new_name='nickname',
        ),
    ]
