# Generated by Django 2.0.3 on 2018-03-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(help_text='用户显示的头像！', upload_to='media', verbose_name='头像'),
        ),
    ]
