# Generated by Django 2.0.3 on 2018-03-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180322_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(help_text='用户显示的头像！', upload_to='upload', verbose_name='头像'),
        ),
    ]
