# Generated by Django 2.0.3 on 2018-03-22 16:17

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180322_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, help_text='可不填！', max_length=100, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, help_text='可不填！', max_length=10, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='/resource/user_image/default.png', help_text='可不设置！', null=True, upload_to='resource/user_image', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='information',
            field=models.TextField(blank=True, help_text='可不填！', null=True, verbose_name='信息'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default='普通用户', help_text='实际展示给他人的名称，可随时更改', max_length=50, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='可不填！', max_length=11, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, '男'), (0, '女'), (-1, '中')], default=-1, help_text='可不填 默认为中性！', null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(error_messages={'unique': '此用户名已被占用！'}, help_text='必填！150个字符或者更少。包含字母，数字和仅有的@/./+/-/_符号，不能与他人重复，不可修改。', max_length=50, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='用户名'),
        ),
    ]
