# Generated by Django 2.0.3 on 2018-03-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180320_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthentication',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, '男'), (0, '女'), (-1, '中')], default=-1, max_length=10, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, '普通用户'), (2, '会员'), (3, '作者')], default=1, max_length=50, null=True, verbose_name='用户类型'),
        ),
    ]
