# Generated by Django 2.0.3 on 2018-03-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180323_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, help_text='用户显示的头像！', null=True, upload_to='upload', verbose_name='头像'),
        ),
    ]
