# Generated by Django 2.0.3 on 2018-03-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180320_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, '男'), (0, '女'), (-1, '中')], default=-1, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, '普通用户'), (2, '会员'), (3, '作者')], default=1, null=True, verbose_name='用户类型'),
        ),
    ]
