# Generated by Django 2.0.3 on 2018-03-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180324_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default='', help_text='实际展示给他人的名称，可随时更改', max_length=50, verbose_name='昵称'),
        ),
    ]
