# Generated by Django 2.0.3 on 2018-03-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180324_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default='用户默认昵称', help_text='实际展示给他人的名称，可随时更改', max_length=50, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.IntegerField(blank=True, choices=[('male', '男'), ('female', '女'), ('neutral', '中')], default=-1, help_text='可不填 默认为中性！', null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.IntegerField(blank=True, choices=[('user', '普通用户'), ('vip', '会员'), ('author', '作者')], default=1, null=True, verbose_name='用户类型'),
        ),
    ]
