# Generated by Django 2.0.3 on 2018-03-24 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20180322_2214'),
        ('user', '0008_usercomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomment',
            name='image',
        ),
        migrations.AddField(
            model_name='usercomment',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='image.Image', verbose_name='图片'),
        ),
    ]
